<?php //if (isset($this->previous)): ?>
	<li><a href="<?= $this->url(array('page' => $this->previous)) ?>">&laquo;</a></li>
<?php //endif;?>
	<?php foreach ($this->pagesInRange as $page){
		if ($page == $this->current){?>
			<li class="active"><a href="<?= $this->url(array('page' => $page)) ?>"><?=$page?></a></li>
		<?php }else{?>
			<li><a href="<?= $this->url(array('page' => $page)) ?>"><?=$page?></a></li>
		<?php ;}
		}?>
<?php if (isset($this->next)): ?>
	<li><a href="<?= $this->url(array('page' => $this->next)) ?>">&raquo;</a></li>
<?php endif;?>