<?php $this->headScript()->appendFile('js/signup.js'); ?>
<?php $this->headScript()->appendFile('js/jquery.form.min.js'); ?>
	<div class="panel panel-default">
		<div class="panel-body">
			<form role="form" method="post">
			 <div class="form-group">
			    <label for="exampleInputEmail1">Nickname</label>
			    <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Enter email" name='mm_display_name'>
			  </div>
			  <div class="form-group">
			    <label for="exampleInputEmail1">Email address</label>
			    <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Enter email"name='mm_email'>
			  </div>
			  <div class="form-group">
			    <label for="exampleInputPassword1">Password</label>
			    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password"name='mm_password'>
			  </div>
			  <div class="form-group">
			    <label for="exampleInputPassword1">Confirm Password</label>
			    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password"name='re_password'>
			  </div>
			  <div class="form-group">
			    <label for="exampleInputFile">File input</label>
			    <input type="file" id="exampleInputFile" name='mm_avatar'>
			    <p class="help-block">Please upload 200 x 200 sized pictures</p>
			  </div>
			  <div style='text-align:center'>
			  	<button type="button" class="btn btn-primary" id='save_member'>Submit</button>
			  </div>
			</form>
		</div>
	</div>

