<?php $this->headScript()->appendFile('ckeditor/ckeditor.js'); ?>
<?php $this->headScript()->appendFile('ckfinder/ckfinder.js'); ?>
<?php $this->headScript()->appendFile('js/view.js'); ?>
<?php $auth = Zend_Auth::getInstance();?>

<div style='width:70%;float:left;'>
		<div class="panel panel-default">
  			<div class="panel-body">
  				<div class="list-group">
			  		<div class="list-group-item active">
			  			<div class="row">
							<div class="col-md-2"><div style='width:100px;height:100px'><img src="<?=($this->blog_data)?'images/member_avatar/'.$this->blog_data->mm_avatar:''?>" class="img-thumbnail"></div></div>
							<div class="col-md-6"><span style='color:#fff'><?=($this->blog_data)?$this->blog_data->mm_display_name:''?></span></div>
							<div class="col-md-4"><div class="text-right"><span style='color:#fff'><?=($this->blog_data)?$this->format_date:''?></span></div></div>
							<div class="col-md-10"><br><h4 style='color:#fff'><?=($this->blog_data)?$this->blog_data->mb_title:''?></h4></div>
							<div class="col-md-10"><div class="text-right"><a class="text-warning" href='<?=$this->url(array('controller'=>'index','action'=>'reply','blog'=>$this->blog_data->mb_id,'page'=>$this->page),null,true) ?>'>Reply</a><span class="text-warning">  |  </span><a class="text-warning" id='popupcited'>Cited Articles</a></div></div>
						</div>
					</div>
				</div>
				<hr>
				<?=($this->blog_data)?$this->blog_data->mb_body:''?>
				<hr>
				
				<div class="panel-body">
				<h4>Tags</h4>
				<?php if($this->tag_data){
						$count = count($this->tag_data);
						$nub = 1;
					foreach ($this->tag_data as $val){
						$str='';
						if($nub!=$count){$str=',';}
						echo '<a href="'.$this->url(array('controller'=>'index','action'=>'search','tag'=>$val['tm_id']),null,true).'">'.$val['tm_name'].'</a>'.$str; 
					$nub++;}
					
				}?>
				</div>
		</div>	
	</div>
</div>		
<div style='width:28%;float:left;margin-left:10px;' id='left_block'>
		<div class="panel panel-danger">
			<div class="panel-body">
			<div style='text-align:center'>
			<h4>Hi!&nbsp;&nbsp;<?=(isset($auth->getStorage()->read()->mm_id)?$auth->getStorage()->read()->mm_display_name:'Anonymous')?></h4>
				<button type="button" class="btn btn-primary btn-lg" name='addpost'>Add Post</button>
			</div>
		   	<form class="navbar-form navbar-left" role="search" method="post" action="index/search">
	      		<div class="form-group">
	        		<input type="text" class="form-control input-sm" placeholder="Search Post Title" name='keyword'>
	      		</div>
	      			<button type="submit" class="btn btn-default btn-sm">Submit</button>
	    	</form>
			</div>
		</div>
	<div class="panel-body">
			<h4>Recent articles response</h4>
			<ul class="list-group">
				<?php if($this->recent_data){
						foreach ($this->recent_data as $val){
					?>
					<a href="<?=$this->url(array('controller'=>'index','action'=>'view','blog'=>$val['mb_id']),null,true) ?>">
					  <li class="list-group-item">
					    
					    
					    <?=$val['mbp_body'] ?><br>
					    <h6 style='text-align:right'>--<?=$val['mb_title'] ?></h6>
					    <span class="badge"><?=$val['mbp_created'] ?> by~<?=$val['user_name'] ?></span><br>
					  </li>
				   </a>
				  <?php }}?>
			</ul>
	</div>
		<div class="panel-body">
			<h4>Popular Articles</h4>
			<ul class="list-group">
				<?php if($this->hot_data){
						foreach ($this->hot_data as $val){
					?>
					<a href="<?=$this->url(array('controller'=>'index','action'=>'view','blog'=>$val['mb_id']),null,true) ?>">
					  <li class="list-group-item">
					    <span class="badge"><?=$val['mb_viewed'] ?></span>
					    <?=$val['mb_title'] ?>
					  </li>
				  </a>
				  <?php }}?>
			</ul>
	</div>
		<div class="panel-body">
			<h4>Articles Category</h4>
			<ul class="list-group">
				<?php if($this->blog_ca_data){
						foreach ($this->blog_ca_data as $val){
					?>
					<a href="<?=$this->url(array('controller'=>'index','action'=>'search','ca'=>$val['mbc_id']),null,true) ?>">
					  <li class="list-group-item">
					  	<span class="badge"><?=$val['mbc_count_nub'] ?></span>
					    <?=$val['mbc_name'] ?>
					  </li>
				  </a>
				  <?php }}?>
			</ul>
		</div>
		<div class="panel-body">
			<h4>Articles Tags</h4>
				<?php if($this->tag_main_data){
					$count = count($this->tag_main_data);
					$nub = 1;
						foreach ($this->tag_main_data as $val){
					?>
					<a href="<?=$this->url(array('controller'=>'index','action'=>'search','tag'=>$val['tm_id']),null,true) ?>">
					<?php $str='';if($nub!=$count){$str=',';}?>
					<?=$val['tm_name'].$str ?>
				  </a>
				  <?php $nub++;}}?>
		</div>
</div>
<div style='width:70%;float:left;'>
<?php if($this->blog_reply){
	$nub =($this->page == 1)?1:($this->page-1)*5+1;
		foreach ($this->blog_reply as $val){
			$src = 'images/index_img/member_defut_cover.gif';
			if(!empty($val['mm_avatar']) && file_exists('images/member_avatar/' . $val['mm_avatar'])){
				$src = 'images/member_avatar/'.$val['mm_avatar'];
			}
?>
		<div class="panel panel-default">
  			<div class="panel-body">
  				<div class="list-group">
			  		<div class="list-group-item">
			  			<div class="row">
							<div class="col-md-1"><div style='width:50px;height:50px'><img src="<?=$src ?>" class="img-thumbnail"></div></div>
							<div class="col-md-11"><span style='color:#666'><?=$val['user_name']?></span></div>
							<div class="col-md-4"><span style='color:#666'><?=$val['mbp_created'].' #'.$nub?></span></div>
						</div>
						<hr>
						<div class="row">
						<?php if($val['mbp_secret'] == 1  && !isset(Zend_Auth::getInstance()->getStorage()->read()->mm_id) ||  $val['mbp_secret'] == 1 && isset(Zend_Auth::getInstance()->getStorage()->read()->mm_id) && $this->blog_data->mb_author !=  Zend_Auth::getInstance()->getStorage()->read()->mm_id ){
						?>
							<div class="col-md-12"><span style='color:#666'><i>悄悄話</i></span></div>
							<?php }else{?>
							<div class="col-md-12"><span style='color:#666'><?=$val['mbp_body']?><?=$val['mbp_secret'] ?></span></div>
							<?php }?>
						</div>
					</div>
				</div>
			</div>
		</div>
	<?php $nub++;}}?>
</div>
<div style='width:70%;float:left;text-align:center'>
	<ul class="pagination">
	<?php if($this->blog_reply_pagnater['total']>5){
				 if ($this->blog_reply_pagnater['rows']){
							echo $this->paginationControl($this->blog_reply_pagnater['rows'], 'Sliding', 'page/page.phtml');
						}
					}
					?>
	</ul>  	
</div>
