<?php $this->headScript()->appendFile('ckeditor/ckeditor.js'); ?>
<?php $this->headScript()->appendFile('ckfinder/ckfinder.js'); ?>
<?php $this->headScript()->appendFile('js/replylist.js'); 
	$auth = Zend_Auth::getInstance();
	$action = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
?>
<div style='text-align:left;height:60px'>
	<h4>Hi!&nbsp;&nbsp;<?=$auth->getStorage()->read()->mm_display_name ?></h4>
	<a class="text-warning" href='<?=$this->url(array('controller'=>'authtodo','action'=>'post'),null,true) ?>' name='delete_post_btn'>Add Post</a>
</div>

<!--<div class="panel panel-default">-->
<ul class="nav nav-tabs">
  <li><a href="<?=$this->url(array('controller'=>'authtodo','action'=>'postlist'),null,true)?>">Post Article</a></li>
  <li class="<?=($action == 'replylist')?'active':'';?>"><a href="<?=$this->url(array('controller'=>'authtodo','action'=>'replylist'),null,true) ?>">Reply</a></li>
  <table class="table">
    <tr><th style='width:55%'>Content</th><th style='width:20%'>Post</th><th style='width:20%'>Create Date</th></tr>
    <?php if($this->reply_data){
    	$nub = 1;
    	foreach ($this->reply_data as $val){
    	?>
    <tr name = 'post_title' style='height:60px' rel="<?=$val['mb_id']?>">
    	<td><?=$val['mbp_body']?> ► <span class="text-primary"><?php 
    	if($val['mbp_status'] == 1){
    		$po_str = 'Release';
    	}
    	if($val['mbp_status'] == 2){
    		$po_str = 'Report';
    	}
    	if($val['mbp_status'] == 3){
    		$po_str = 'Disabled';
    	}
    	echo $po_str; 
    	?></span>
    	<div name='post_tool' >
	    	<a class="text-warning" href="<?=$this->url(array('controller'=>'index','action'=>'reply','blog'=>$val['mb_id'],'post'=>$val['mbp_id']),null,true) ?>">Editor&nbsp;|&nbsp;</a>
	    	<a class="text-warning" name='delete_post_btn'>Delete&nbsp;|&nbsp;</a>
		</div>			
		</td>
		<td><a href="<?=$this->url(array('controller'=>'authtodo','action'=>'post','blog'=>$val['mb_id']),null,true) ?>"><?=$val['mb_title']?></a></td>
		<td><?=$val['mbp_created']?></td>
	</tr>
	<?php $nub++;}}?>
  </table>
  </ul>